# Generated by Django 4.0.2 on 2022-02-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('game', models.AutoField(primary_key=True, serialize=False)),
                ('round', models.IntegerField()),
                ('team_1_score', models.IntegerField(default=0)),
                ('team_2_score', models.IntegerField(default=0)),
                ('team_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='core.team')),
                ('team_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='core.team')),
            ],
        ),
    ]
