# Generated by Django 4.0.2 on 2022-02-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_defeats_team_draws_team_goals_conceded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='game',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='battle',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
