# Generated by Django 4.0.2 on 2022-02-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_battle_id_alter_battle_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.tournament'),
            preserve_default=False,
        ),
    ]
