# Generated by Django 4.0.2 on 2022-02-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_battle_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
