# Generated by Django 4.0.2 on 2022-03-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_battle_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.CharField(default='None', max_length=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(default='not started', max_length=100),
        ),
    ]
