# Generated by Django 4.0.2 on 2022-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_battle_winner_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='false_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
    ]
