# Generated by Django 4.0.2 on 2022-03-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team_false_team_tournament_current_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.CharField(default='knockout', max_length=100),
        ),
    ]
