# Generated by Django 4.0.2 on 2022-03-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_team_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
